In [1]:
import numpy as np

In [2]:
b1 = np.matrix([[1,0],[0,0]]) # |0><0|
b2 = np.matrix([[0,0],[0,1]]) # |1><1|

H = np.matrix([[1,1],[1,-1]]) * (1/np.sqrt(2)) # Hadamard matrix
S = np.matrix([[1,0],[0,1j]]) # Phase matrix

I = np.matrix([[1,0],[0,1]]) # Identity matrix
X = np.matrix([[0,1],[1,0]]) # Pauli-X matrix
Y = np.matrix([[0,-1j],[1j,0]]) # Pauli-Y matrix
Z = np.matrix([[1,0],[0,-1]]) # Pauli-Z matrix

measure_X = H
measure_Y = H @ S
measure_Z = I

In [9]:
print(3* np.trace(I @ (measure_X.H @ b1 @ measure_X)))
print(3* np.trace(I @ (measure_X.H @ b2 @ measure_X)))
print(3* np.trace(I @ (measure_Y.H @ b1 @ measure_Y)))
print(3* np.trace(I @ (measure_Y.H @ b2 @ measure_Y)))
print(3* np.trace(I @ (measure_Z.H @ b1 @ measure_Z)))
print(3* np.trace(I @ (measure_Z.H @ b2 @ measure_Z)))

2.999999999999999
2.999999999999999
(2.999999999999999+0j)
(2.999999999999999+0j)
3
3


In [19]:
print(measure_X @ X @ measure_X.H)

[[ 1.00000000e+00 -2.23711432e-17]
 [ 2.23711432e-17 -1.00000000e+00]]


In [4]:
print(np.kron(Z, Z))

[[ 1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0  1]]


In [5]:
print(I @ (measure_Y.H @ b1 @ measure_Y))
print(I @ (measure_X.H @ b1 @ measure_X))
print(I @ (measure_Z.H @ b1 @ measure_Z))

[[0.5+0.j  0. +0.5j]
 [0. -0.5j 0.5+0.j ]]
[[0.5 0.5]
 [0.5 0.5]]
[[1 0]
 [0 0]]


In [6]:
# print("X-basis states:\n")
# print(measure_X.H @ b1 @ measure_X)
# print(measure_X.H @ b2 @ measure_X)

# print("Y-basis states:\n")
# print(measure_Y.H @ b1 @ measure_Y)
# print(measure_Y.H @ b2 @ measure_Y)

# print("Z-basis states:\n")
# print(measure_Z.H @ b1 @ measure_Z)
# print(measure_Z.H @ b2 @ measure_Z)

print(np.trace(I @ (measure_X.H @ b1 @ measure_X)))
print(np.trace(X @ (measure_X.H @ b1 @ measure_X)))
print(np.trace(Y @ (measure_X.H @ b1 @ measure_X)))
print(np.trace(Z @ (measure_X.H @ b1 @ measure_X)))
print("\n")

print(np.trace(I @ (measure_X.H @ b2 @ measure_X)))
print(np.trace(X @ (measure_X.H @ b2 @ measure_X)))
print(np.trace(Y @ (measure_X.H @ b2 @ measure_X)))
print(np.trace(Z @ (measure_X.H @ b2 @ measure_X)))
print("\n")

print(np.trace(I @ (measure_Y.H @ b1 @ measure_Y)))
print(np.trace(X @ (measure_Y.H @ b1 @ measure_Y)))
print(np.trace(Y @ (measure_Y.H @ b1 @ measure_Y)))
print(np.trace(Z @ (measure_Y.H @ b1 @ measure_Y)))
print("\n")

print(np.trace(I @ (measure_Y.H @ b2 @ measure_Y)))
print(np.trace(X @ (measure_Y.H @ b2 @ measure_Y)))
print(np.trace(Y @ (measure_Y.H @ b2 @ measure_Y)))
print(np.trace(Z @ (measure_Y.H @ b2 @ measure_Y)))
print("\n")

print(np.trace(I @ (measure_Z.H @ b1 @ measure_Z)))
print(np.trace(X @ (measure_Z.H @ b1 @ measure_Z)))
print(np.trace(Y @ (measure_Z.H @ b1 @ measure_Z)))
print(np.trace(Z @ (measure_Z.H @ b1 @ measure_Z)))
print("\n")

print(np.trace(I @ (measure_Z.H @ b2 @ measure_Z)))
print(np.trace(X @ (measure_Z.H @ b2 @ measure_Z)))
print(np.trace(Y @ (measure_Z.H @ b2 @ measure_Z)))
print(np.trace(Z @ (measure_Z.H @ b2 @ measure_Z)))
print("\n")

0.9999999999999998
0.9999999999999998
0j
0.0


0.9999999999999998
-0.9999999999999998
0j
0.0


(0.9999999999999998+0j)
0j
(-0.9999999999999998+0j)
0j


(0.9999999999999998+0j)
0j
(0.9999999999999998+0j)
0j


1
0
0j
1


1
0
0j
-1




In [7]:
ghz = [[0.5,0,0,0,0,0,0,0.5],
       [0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0],
       [0.5,0,0,0,0,0,0,0.5]]

print(np.trace(np.kron(Y, (np.kron(Y, Y))) @ np.matrix(ghz)))

0j
