In [9]:
import numpy as np

In [10]:
b1 = np.matrix([[1,0],[0,0]]) # |0><0|
b2 = np.matrix([[0,0],[0,1]]) # |1><1|

H = np.matrix([[1,1],[1,-1]]) * (1/np.sqrt(2)) # Hadamard matrix
S = np.matrix([[1,0],[0,1j]]) # Phase matrix

I = np.matrix([[1,0],[0,1]]) # Identity matrix
X = np.matrix([[0,1],[1,0]]) # Pauli-X matrix
Y = np.matrix([[0,-1j],[1j,0]]) # Pauli-Y matrix
Z = np.matrix([[1,0],[0,-1]]) # Pauli-Z matrix

measure_X = H
measure_Y = H @ S
measure_Z = I

print("X-basis states:\n")
print(measure_X.T @ b1 @ measure_X)
print(measure_X.T @ b2 @ measure_X)

print("Y-basis states:\n")
print(measure_Y.T @ b1 @ measure_Y)
print(measure_Y.T @ b2 @ measure_Y)

print("Z-basis states:\n")
print(measure_Z.T @ b1 @ measure_Z)
print(measure_Z.T @ b2 @ measure_Z)

np.trace(Y @ (measure_Z.T @ b1 @ measure_Z))

X-basis states:

[[0.5 0.5]
 [0.5 0.5]]
[[ 0.5 -0.5]
 [-0.5  0.5]]
Y-basis states:

[[ 0.5+0.j   0. +0.5j]
 [ 0. +0.5j -0.5+0.j ]]
[[ 0.5+0.j   0. -0.5j]
 [ 0. -0.5j -0.5+0.j ]]
Z-basis states:

[[1 0]
 [0 0]]
[[0 0]
 [0 1]]


0j